import type { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";

import { Questrial } from "next/font/google";

import Header from "@/components/header";

import "./globals.css";

const font = Questrial({
  weight: "400",
  display: "swap",
  subsets: ["latin-ext"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Hasan Harman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className="max-w-3xl mx-auto space-y-6 my-5 px-5 md:px-0">
          <Header fontClass={font.className} />
          <main className={font.className}>{children}</main>
        </body>
      </html>
    </ViewTransitions>
  );
}
