import fs from "fs";
import path from "path";

export type RegistryFile = {
  path: string;
  content: string;
  type: string;
  target?: string;
};

export type RegistryItem = {
  name: string;
  title?: string;
  description?: string;
  dependencies?: string[];
  registryDependencies?: string[];
  files: RegistryFile[];
};

/**
 * Reads a built registry item from `public/r/<name>.json`. These files are
 * generated by `npm run registry:build` and carry the component source in
 * `files[].content`, so the lab detail pages can render code without a
 * second copy of it.
 */
export function getRegistryItem(name: string): RegistryItem | null {
  try {
    const file = path.join(process.cwd(), "public", "r", `${name}.json`);
    return JSON.parse(fs.readFileSync(file, "utf8")) as RegistryItem;
  } catch {
    return null;
  }
}
